apiVersion: v2
name: cilium
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: cilium
    repository: https://helm.cilium.io/
    version: 1.17.3
