---
loki:
  global:
    # -- Overrides the Docker registry globally for all images (standard format)
    imageRegistry: null
    image:
      # -- Overrides the Docker registry globally for all images (deprecated, use global.imageRegistry)
      registry: null
