---
alloy:
  alloy:
    configMap:
      # -- Create a new ConfigMap for the config file.
      create: true
      # -- Content to assign to the new ConfigMap.  This is passed into `tpl` allowing for templating from values.
      content: |
        logging {
          level = "info"
          format = "logfmt"
        }

      # -- Name of existing ConfigMap to use. Used when create is false.
      name: null
      # -- Key in ConfigMap to get config from.
      key: null

    clustering:
      # -- Deploy Alloy in a cluster to allow for load distribution.
      enabled: false

      # -- Name for the Alloy cluster. Used for differentiating between clusters.
      name: ""

      # -- Name for the port used for clustering, useful if running inside an Istio Mesh
      portName: http
