apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: https-vault
  namespace: vault
spec:
  parentRefs:
  - name: tls-gateway
    namespace: kube-system
  hostnames:
  - "vault.unixworld.io"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: vault
      port: 8200
