apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: redirect-to-proxy-cache
  annotations:
    policies.kyverno.io/title: Redirect Docker Hub to Local Proxy Cache
spec:
  background: false
  rules:
    - name: mutate-standard-containers
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                - docker-registry
      mutate:
        foreach:
          - list: "request.object.spec.containers"
            patchesJson6902: |-
              - op: replace
                path: "/spec/containers/{{pathIndex}}/image"
                value: "{{ regex_replace_all('^docker.io/([^/]+)$', '{{element.image}}', 'registry.unixworld.io/library/${1}') || regex_replace_all('^docker.io/', '{{element.image}}', 'registry.unixworld.io/') }}"

    - name: mutate-init-containers
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                - docker-registry
      preconditions:
        all:
        - key: "{{ request.object.spec.initContainers[].name | length(@) }}"
          operator: GreaterThan
          value: 0
      mutate:
        foreach:
          - list: "request.object.spec.initContainers"
            patchesJson6902: |-
              - op: replace
                path: "/spec/initContainers/{{pathIndex}}/image"
                value: "{{ regex_replace_all('^docker.io/([^/]+)$', '{{element.image}}', 'registry.unixworld.io/library/${1}') || regex_replace_all('^docker.io/', '{{element.image}}', 'registry.unixworld.io/') }}"
