apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: redirect-dockerhub-to-private-registry
  annotations:
    policies.kyverno.io/title: Redirect Docker Hub to Private Registry
    policies.kyverno.io/category: Image Management
spec:
  background: false
  rules:
    - name: rewrite-containers
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - kyverno
                - docker-registry
      mutate:
        foreach:
          - list: "request.object.spec.containers"
            preconditions:
              all:
                - key: "{{ element.image }}"
                  operator: Equals
                  value: "{{ regex_match('^(docker\\.io|index\\.docker\\.io)/.+', '{{element.image}}') }}"
            patchStrategicMerge:
              spec:
                containers:
                  - name: "{{ element.name }}"
                    image: "{{ regex_replace_all('^(docker\\.io|index\\.docker\\.io)/(?!.+/)', '{{element.image}}', 'registry.unixworld.io/library/') | regex_replace_all('^(docker\\.io|index\\.docker\\.io)/', '@', 'registry.unixworld.io/') }}"
    - name: rewrite-init-containers
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - kyverno
                - docker-registry
      preconditions:
        all:
          - key: "{{ request.object.spec.initContainers || '' | length(@) }}"
            operator: GreaterThan
            value: 0
      mutate:
        foreach:
          - list: "request.object.spec.initContainers"
            preconditions:
              all:
                - key: "{{ element.image }}"
                  operator: Equals
                  value: "{{ regex_match('^(docker\\.io|index\\.docker\\.io)/.+', '{{element.image}}') }}"
            patchStrategicMerge:
              spec:
                initContainers:
                  - name: "{{ element.name }}"
                    image: "{{ regex_replace_all('^(docker\\.io|index\\.docker\\.io)/(?!.+/)', '{{element.image}}', 'registry.unixworld.io/library/') | regex_replace_all('^(docker\\.io|index\\.docker\\.io)/', '@', 'registry.unixworld.io/') }}"
