apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: ceph-csi
spec:
  provider:
    vault:
      server: "http://vault.vault:8200"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: csi-cephfs-secret
  namespace: ceph-csi
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: csi-cephfs-secret
  data:
  - secretKey: userID
    remoteRef:
      key: ceph
      property: userID
  - secretKey: userKey
    remoteRef:
      key: ceph
      property: userKey
