apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: monitoring
spec:
  provider:
    vault:
      server: "http://vault.vault:8200"
      path: "grafana"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
          namespace: monitoring
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-password
  namespace: monitoring
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: grafana-admin-password
  data:
  - secretKey: admin-user
    remoteRef:
      key: secret
      property: admin-user
  - secretKey: admin-password
    remoteRef:
      key: secret
      property: admin-password
