---
authentik:
 secret_key: "WL5lg3Cv38DM3f9eGDbLi4ekp/2uws"
 # This sends anonymous usage-data, stack traces on errors and
 # performance data to sentry.io, and is fully opt-in
 error_reporting:
   enabled: true
 postgresql:
   password: "2V/Z2Qfrn2Mx87cL006wDd50AFEdbCEhV"

server:
  route:
    main:
      enabled: true
      hostnames:
        - authentik.unixworld.io
      parentRefs:
        - name: tls-gateway
          namespace: kube-system
      matches:
        - path:
            type: PathPrefix
            value: /

postgresql:
  enabled: true
  auth:
    password: "k5rrts+zIgTlQIFjxfGiS/t9sVj2piPiL0xgY"
