apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: openbao-backend
  namespace: authentik
spec:
  provider:
    vault:
      server: "http://openbao.openbao:8200"
      path: "authentik"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "openbao-token"
          key: "token"
          namespace: authentik
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secret
  namespace: authentik
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: openbao-backend
    kind: SecretStore
  target:
    name: authentik-secret
  data:
  - secretKey: AUTHENTIK_SECRET_KEY
    remoteRef:
      key: secret
      property: AUTHENTIK_SECRET_KEY
  - secretKey: AUTHENTIK_POSTGRESQL__PASSWORD
    remoteRef:
      key: secret
      property: AUTHENTIK_POSTGRESQL__PASSWORD
  - secretKey: AUTHENTIK_POSTGRESQL__HOST
    remoteRef:
      key: secret
      property: AUTHENTIK_POSTGRESQL__HOST
  - secretKey: AUTHENTIK_BOOTSTRAP_PASSWORD
    remoteRef:
      key: secret
      property: AUTHENTIK_BOOTSTRAP_PASSWORD
