apiVersion: v2
name: vault
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: vault
    repository: https://helm.releases.hashicorp.com
    version: 0.30.0
