apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: docker-registry
spec:
  provider:
    vault:
      server: "http://openbao.vault:8200"
      path: "docker-registry"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
          namespace: docker-registry
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: docker-registry-secret
  namespace: docker-registry
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: docker-registry-secret
  data:
  - secretKey: s3AccessKey
    remoteRef:
      key: secret
      property: s3AccessKey
  - secretKey: s3SecretKey
    remoteRef:
      key: secret
      property: s3SecretKey
  - secretKey: haSharedSecret
    remoteRef:
      key: secret
      property: haSharedSecret
  - secretKey: proxyUsername
    remoteRef:
      key: secret
      property: proxyUsername
  - secretKey: proxyPassword
    remoteRef:
      key: secret
      property: proxyPassword
