apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: gitlab
spec:
  provider:
    vault:
      server: "http://vault.vault:8200"
      path: "gitlab"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
          namespace: gitlab
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-root-password
  namespace: gitlab
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: gitlab-root-password
  data:
  - secretKey: password
    remoteRef:
      key: secret
      property: password
