apiVersion: v2
name: velero
description: A Helm chart for Kubernetes
type: application
version: 10.0.5
appVersion: 1.16.1
dependencies:
  - name: velero
    repository: https://vmware-tanzu.github.io/helm-charts
    version: 10.0.5
