---
velero:
  configuration:
    backupStorageLocation:
    - name: backup-storage
      provider: "aws"
      bucket: "velero-backup"
      default: false
      accessMode: ReadWrite
      config:
        region: default
        s3ForcePathStyle: true
        s3Url: http://192.168.1.21:7480
    volumeSnapshotLocation:
    - name: volume-snapshot
      provider: aws
      config:
        region: default
    defaultVolumesToFsBackup: true
  deployNodeAgent: true
  nodeAgent:
    podVolumePath: /var/lib/kubelet/pods
  credentials:
    useSecret: true
    name: minio-secret
    existingSecret: minio-secret
  kubectl:
    image:
      repository: docker.io/bitnamilegacy/kubectl
      tag: 1.33.4
  initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.13.1
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /target
          name: plugins

  schedules:
    daily-cluster-backup:
      disabled: false
      schedule: "0 11 * * *"
      useOwnerReferencesInBackup: false
      paused: false
      skipImmediately: false
      template:
        ttl: "240h"
        storageLocation: backup-storage
        includedNamespaces:
          - '*'
        excludedNamespaces:
          - kube-system
          - velero
        defaultVolumesToFsBackup: true
