apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: openbao-backend
  namespace: alloy
spec:
  provider:
    vault:
      server: "http://openbao.openbao:8200"
      path: "prometheus"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "openbao-token"
          key: "token"
          namespace: alloy
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki-auth
  namespace: alloy
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: openbao-backend
    kind: SecretStore
  target:
    name: loki-auth
  data:
  - secretKey: password
    remoteRef:
      key: loki
      property: password
