apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: openbao-backend
  namespace: mimir
spec:
  provider:
    vault:
      server: "http://openbao.openbao:8200"
      path: "mimir"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "openbao-token"
          key: "token"
          namespace: mimir
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mimir-secret
  namespace: mimir
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: openbao-backend
    kind: SecretStore
  target:
    name: mimir-secret
  data:
  - secretKey: .htpasswd
    remoteRef:
      key: secret
      property: .htpasswd
